pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage('Checkout') {
            steps {
                echo 'Obteniendo código fuente...'
                git branch: 'main', url: 'https://github.com/raaulroodriguez/DespliegueDAW.git'
            }
        }
        
        stage('Build') {
            steps {
                echo 'Compilando proyecto con Maven...'
                sh 'mvn -f CalculadoraWeb/pom.xml clean package'
            }
        }
        stage('Compile') {
            steps {
                echo 'Compilando proyecto con Maven...'
                sh 'mvn -f CalculadoraWeb/pom.xml compile'
            }
        }
        stage('Test') {
            steps {
                echo 'Ejecutando pruebas...'
                sh 'mvn -f CalculadoraWeb/pom.xml test'
            }
        }
        stage('Deploy') {
    steps {
        echo 'Desplegando a Tomcat...'
        sh '''
            echo "Copiando WAR al volumen compartido con Windows..."
            cp CalculadoraWeb/target/*.war /var/jenkins_home/tomcat-deploy/CalculadoraWeb.war
        '''
    }
}
    }
    post {
        success {
            echo '✅ Pipeline completado exitosamente!'
        }
        failure {
            echo '❌ Pipeline falló. Revisar logs.'
        }
    }
}